# Generated by Django 5.0.2 on 2024-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Summary',
            field=models.TextField(),
        ),
    ]
